-- AlterTable
ALTER TABLE "agents" ADD COLUMN     "roi" DECIMAL(15,4) NOT NULL DEFAULT 0.00,
ADD COLUMN     "total_bet_amount" DECIMAL(15,2) NOT NULL DEFAULT 0.00,
ADD COLUMN     "total_bets" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "total_winnings" DECIMAL(15,2) NOT NULL DEFAULT 0.00,
ADD COLUMN     "win_rate" DECIMAL(5,4) NOT NULL DEFAULT 0.00,
ADD COLUMN     "won_bets" INTEGER NOT NULL DEFAULT 0;
